name: Release to PyPI

#on:
#  push:
#    branches:
#      - "main"
#    paths:
#      - "CHANGELOG.md"
#  workflow_dispatch:

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  prepare-release:
    name: Build Release
    uses: ./.github/workflows/python-build-release.yml

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs:
    - prepare-release
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/telicent-lib

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Confirm All's OK
      run: |
        ls ./*

#    - name: Publish distribution to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
