name: Release to PyPI

#on:
#  push:
#    branches:
#      - "main"
#    paths:
#      - "CHANGELOG.md"
#  workflow_dispatch:

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  test-and-build:
    name: Python Tests
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    uses: telicent-oss/shared-workflows/.github/workflows/python-test-library.yml@TPT-90-Test-scanning-of-a-Python-SBOM
    with:
      PYTHON_VERSION: ${{ matrix.python-version }}
      BUILD: false

  prepare-build-release:
    name: Prepare and Build Release
    uses: telicent-oss/shared-workflows/.github/workflows/python-build-release.yml@TPT-90-Test-scanning-of-a-Python-SBOM

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs:
    - prepare-build-release
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/telicent-lib

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Confirm All's OK
      run: |
        ls ./*

#    - name: Publish distribution to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
