name: Release to PyPI

on:
  push:
    branches:
      - "main"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  test-and-build:
    name: Python Tests
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    uses: telicent-oss/shared-workflows/.github/workflows/python-test-library.yml@main
    with:
      PYTHON_VERSION: ${{ matrix.python-version }}
      SKIP_BUILD: true

  prepare-build-release:
    name: Prepare and Build Release
    uses: telicent-oss/shared-workflows/.github/workflows/python-build-release.yml@main
    with:
      PACKAGE: telicent_lib

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs:
    - prepare-build-release
    - test-and-build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/telicent-lib

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
