name: Python Test Build

on:
  pull_request:
    branches:
      - "release-please*"
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  test-and-build:
    name: Python Test and Build
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    uses: telicent-oss/shared-workflows/.github/workflows/python-ci-qa.yml@TPT-305-windows-runners
    with:
      PYTHON_VERSION: ${{ matrix.python-version }}

