name: Python Vuln Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  scan_pr:
    uses: telicent-oss/shared-workflows/.github/workflows/python-generate-and-scan-application.yml@vuln-scan-improvements
    with:
      SCAN_NAME: ${{ github.run_number }}
